/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_freedom_opensl_OpenSLManager */

#ifndef _Included_cn_freedom_opensl_OpenSLManager
#define _Included_cn_freedom_opensl_OpenSLManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    createSLEngine
 * Signature: (II)I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_createSLEngine
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    deleteSlEngine
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_deleteSlEngine
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    createAudioPlayer
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_createAudioPlayer
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    deleteAudioPlayer
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_deleteAudioPlayer
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    startPlayout
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_startPlayout
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    stopPlayout
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_stopPlayout
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    createAudioRecorder
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_createAudioRecorder
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    deleteAudioRecorder
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_deleteAudioRecorder
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    startRecording
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_startRecording
  (JNIEnv *, jobject);

/*
 * Class:     cn_freedom_opensl_OpenSLManager
 * Method:    stopRecording
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_cn_freedom_opensl_OpenSLManager_stopRecording
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
